import localFont from "next/font/local";
import "./globals.css";
import 'swiper/css';

const tekoFont = localFont({
  src: "./fonts/Teko-Regular.ttf",
  variable: "--font-Teko",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${tekoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
